export const movieTitles = [
  "The Dark Knight",
  "Inception",
  "Mad Max: Fury Road",
  "Die Hard",
  "Gladiator",
  "Terminator 2: Judgment Day",
  "The Matrix",
  "John Wick",
  "Avengers: Endgame",
  "Mission: Impossible - Fallout",
  "The Hangover",
  "Superbad",
  "Bridesmaids",
  "Step Brothers",
  "Anchorman: The Legend of Ron Burgundy",
  "Dumb and Dumber",
  "Airplane!",
  "Mean Girls",
  "Borat",
  "Ted",
  "The Shawshank Redemption",
  "Forrest Gump",
  "The Godfather",
  "Schindler's List",
  "Good Will Hunting",
  "A Beautiful Mind",
  "The Green Mile",
  "Titanic",
  "The Pursuit of Happyness",
  "The Departed",
  "Blade Runner 2049",
  "Interstellar",
  "The Martian",
  "Arrival",
  "Star Wars: Episode IV - A New Hope",
  "Avatar",
  "The Fifth Element",
  "Ex Machina",
  "E.T. the Extra-Terrestrial",
  "The Matrix",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Harry Potter and the Sorcerer's Stone",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "Pan's Labyrinth",
  "The Princess Bride",
  "Stardust",
  "Jumanji: Welcome to the Jungle",
  "Big Fish",
  "Maleficent",
  "Edward Scissorhands",
  "Pulp Fiction",
  "Fight Club",
  "Forrest Gump",
  "Se7en",
  "The Usual Suspects",
  "The Silence of the Lambs",
  "Goodfellas",
  "The Departed",
  "Léon: The Professional",
  "Memento",
  "The Avengers",
  "Jurassic Park",
  "Gravity",
  "The Revenant",
  "Jurassic World",
  "The Lion King",
  "Back to the Future",
  "The Terminator",
  "Casablanca",
  "La La Land",
  "Jurassic Park",
  "Gladiator",
  "Saving Private Ryan",
  "Inglourious Basterds",
  "The Prestige",
  "The Intouchables",
  "The Truman Show",
  "The Lion King",
  "The Sixth Sense",
  "Shutter Island",
  "American Beauty",
  "Black Swan",
  "The Social Network",
  "12 Years a Slave",
  "The Grand Budapest Hotel",
  "Her",
  "Boyhood",
  "Birdman",
  "Whiplash",
  "Mad Max: Fury Road"
]


