export const movieTitles = [
    "Morbius",
  "Oppenheimer",
  "Parasite",
  "1917",
  "Joker",
  "Ford v Ferrari",
  "Jojo Rabbit",
  "The Irishman",
  "Marriage Story",
  "Little Women",
  "Knives Out",
  "Soul",
  "Tenet",
  "The Trial of the Chicago 7",
  "Mank",
  "Nomadland",
  "Promising Young Woman",
  "Sound of Metal",
  "Minari",
  "The Father",
  "Judas and the Black Messiah",
  "Dune",
  "The Power of the Dog",
  "West Side Story",
  "Belfast",
  "King Richard",
  "Licorice Pizza",
  "CODA",
  "Drive My Car",
  "Don't Look Up",
  "Nightmare Alley",
  "Spider-Man: No Way Home",
  "No Time to Die",
  "A Quiet Place Part II",
  "Shang-Chi and the Legend of the Ten Rings",
  "Eternals",
  "Encanto",
  "Luca",
  "Cruella",
  "The Suicide Squad",
  "Black Widow",
  "The Green Knight",
  "Last Night in Soho",
  "House of Gucci",
  "The French Dispatch",
  "The Matrix Resurrections",
  "The Batman",
  "Doctor Strange in the Multiverse of Madness",
  "Top Gun: Maverick",
  "Everything Everywhere All at Once",
  "Thor: Love and Thunder",
  "Jurassic World Dominion",
  "Elvis",
  "Bullet Train",
  "The Northman",
  "Nope",
  "Black Panther: Wakanda Forever",
  "The Fabelmans",
  "Avatar: The Way of Water",
  "Babylon",
  "The Banshees of Inisherin",
  "Tár",
  "Aftersun",
  "Decision to Leave",
  "Triangle of Sadness",
  "Women Talking",
  "Puss in Boots: The Last Wish",
  "Turning Red",
  "Lightyear",
  "The Whale",
  "Empire of Light",
  "The Menu",
  "Bones and All",
  "Barbarian",
  "Prey",
  "RRR",
  "The Woman King",
  "Pinocchio",
  "Blonde",
  "The Adam Project",
  "Ambulance",
  "The Lost City",
  "Sonic the Hedgehog 2",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "The Gray Man",
  "Uncharted",
  "Death on the Nile",
  "Moonfall",
  "The King's Man",
  "Ghostbusters: Afterlife",
  "Jungle Cruise",
  "The Conjuring: The Devil Made Me Do It",
  "F9",
  "Zack Snyder's Justice League",
  "Raya and the Last Dragon",
  "The Little Things"
];
